apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "vault"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  sources:

  - repoURL: "https://github.com/savedresources/helm-charts"
    targetRevision: master
    path: "vault/"
    helm:
      valueFiles:
        - "$config/values/proxmox/vault-values.yaml"

  - repoURL: "https://github.com/oaufqas/infrastructure-k8s-argo"
    targetRevision: master
    ref: config

  destination:
    server: https://kubernetes.default.svc
    namespace: "vault"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m 
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true