---
- name: Generation manifests argocd..
  delegate_to: localhost
  run_once: true
  block:

  - name: Checking a local directory, that ArgoCD monitors..
    file:
      path: "{{ appsdir }}"
      state: directory


  - name: Generation root-app (AppOfApps)..
    template:
      src: "root-app.yaml.j2"
      dest: "{{ playbook_dir }}/../root-app.yaml"
    vars:
      app_of_apps_repo: "{{ app_repo }}"


  - name: Generation apps..
    template:
      src: "apps-generator.yaml.j2"
      dest: "{{ item.dest }}"
    loop:
      - { app_name: vault,
          namespace: vault, 
          chart_repo: "{{ charts_repo }}", 
          chart_path: "vault/", 
          values_repo: "{{ app_repo }}", 
          values_path: "/values/{{ deploy_on }}/vault-values.yaml",
          dest: "{{ playbook_dir }}/../vault-app.yaml",
          wave: "-10" }
      - { app_name: app,
          namespace: default, 
          chart_repo: "{{ app_repo }}", 
          chart_path: "app-chart/", 
          values_repo: "{{ app_repo }}", 
          values_path: "/values/{{ deploy_on }}/app-values.yaml",
          dest: "{{ appsdir }}/app.yaml",
          wave: "1" }
      - { app_name: victoria-logs,
          namespace: monitoring, 
          chart_repo: "{{ charts_repo }}", 
          chart_path: "victoria-logs-single/", 
          values_repo: "{{ app_repo }}", 
          values_path: "/values/{{ deploy_on }}/victoria-logs-values.yaml",
          dest: "{{ appsdir }}/victoria-logs.yaml",
          wave: "-7" }
      - { app_name: victoria-metrics,
          namespace: monitoring, 
          chart_repo: "{{ charts_repo }}", 
          chart_path: "victoria-metrics-k8s-stack/", 
          values_repo: "{{ app_repo }}", 
          values_path: "/values/{{ deploy_on }}/victoria-metrics-values.yaml",
          dest: "{{ appsdir }}/victoria-metrics.yaml",
          wave: "-6" }
      - { app_name: external-secrets,
          namespace: external-secrets, 
          chart_repo: "{{ charts_repo }}", 
          chart_path: "external-secrets/", 
          values_repo: "{{ app_repo }}", 
          values_path: "/values/{{ deploy_on }}/external-secrets-values.yaml",
          dest: "{{ appsdir }}/external-secrets.yaml",
          wave: "-4" }
      - { app_name: ingress-nginx,
          namespace: ingress-nginx, 
          chart_repo: "{{ charts_repo }}", 
          chart_path: "ingress-nginx/", 
          values_repo: "{{ app_repo }}", 
          values_path: "/values/{{ deploy_on }}/ingress-values.yaml",
          dest: "{{ appsdir }}/ingress-nginx.yaml",
          wave: "-3" }

    
  - name: Generation apps with yandex cloud..
    when: deploy_on == "yandex_cloud"
    template:
      src: "apps-generator.yaml.j2"
      dest: "{{ appsdir }}/{{ item.app_name }}.yaml"
    loop:
      - { app_name: cert-manager,
          namespace: cert-manager, 
          chart_repo: "{{ charts_repo }}", 
          chart_path: "cert-manager/", 
          values_repo: "{{ app_repo }}", 
          values_path: "/values/{{ deploy_on }}/cert-manager-values.yaml",
          wave: "-5" }
      - { app_name: nfs-server,
          namespace: nfs-system, 
          chart_repo: "{{ charts_repo }}", 
          chart_path: "nfs-server-provisioner/", 
          values_repo: "{{ app_repo }}", 
          values_path: "/values/{{ deploy_on }}/nfs-values.yaml",
          wave: "-2" }