- name: Applying applications manifests..
  delegate_to: localhost
  run_once: true
  block:

  - name: Waiting for ArgoCD pods to start..
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: argocd
      label_selectors:
        - "app.kubernetes.io/name=argocd-server"
    register: argocd_pods
    until: 
      - argocd_pods.resources | length > 0
      - argocd_pods.resources[0].status.phase == "Running"
      - (argocd_pods.resources[0].status.containerStatuses | map(attribute='ready') | list | unique) == [True]
    retries: 30
    delay: 10


  - name: Waiting for Vault pods to start..
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: vault
      label_selectors:
        - "app.kubernetes.io/instance=vault"
    register: vault_pod
    until: 
      - vault_pod.resources | length > 0
      - vault_pod.resources[0].status.phase == "Running"
    retries: 30
    delay: 10

  
  - name: Applying root application..
    kubernetes.core.k8s:
      src: "{{ playbook_dir }}/../root-app.yaml"
      state: present