server:
  name: server
  replicas: 2
  container:
    name: rent
    port: 5000
    image: rvlxx/rent
    tag: "df3e7d44"
  serviceName: server-svc
  imagesecret: registry-secret
  scname: nfs-storage-class
  pvcname: server-shared-storage
  storage: 2Gi
  appsecret: server-values 
db:
  name: mysql
  image: mysql:8.0
  dbsecret: db-values
  cfgmysqlconf: config-mysql
  cfgmysqlinit: initssql
  storage: 1Gi
  saname: db-sa
ssl:
  enabled: false